# Generated by Django 3.2.6 on 2021-09-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_auto_20180501_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
