# Generated by Django 3.2.6 on 2021-11-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicontest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproblem',
            name='p_type',
            field=models.TextField(null=True),
        ),
    ]
