# Generated by Django 3.2.6 on 2021-08-26 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aicontest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiproblem',
            old_name='hint',
            new_name='testhint',
        ),
    ]
