# Generated by Django 3.2.6 on 2021-11-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicontest', '0002_aiproblem_p_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproblem',
            name='migrate_test',
            field=models.TextField(null=True),
        ),
    ]
