# Generated by Django 3.2.6 on 2021-08-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aicontest', '0002_rename_hint_aiproblem_testhint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiproblem',
            old_name='input_description',
            new_name='summary_description',
        ),
    ]
