# Generated by Django 3.2.6 on 2021-08-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aicontest', '0003_rename_input_description_aiproblem_summary_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiproblem',
            old_name='output_description',
            new_name='rule_description',
        ),
    ]
