# Generated by Django 3.2.6 on 2021-11-04 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aicontest', '0003_aiproblem_migrate_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiproblem',
            name='migrate_test',
        ),
    ]
