# Generated by Django 3.2.6 on 2021-11-05 05:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aicontest', '0004_remove_aiproblem_migrate_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproblem',
            name='rank',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
