# Generated by Django 3.2.6 on 2021-08-26 11:44

from django.db import migrations
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('aicontest', '0004_rename_output_description_aiproblem_rule_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproblem',
            name='schedule_description',
            field=utils.models.RichTextField(null=True),
        ),
    ]
