# Generated by Django 3.2.6 on 2021-11-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicontest', '0005_aiproblem_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproblem',
            name='password',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
