# Generated by Django 3.2.6 on 2021-11-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicontest', '0006_aiproblem_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproblem',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
