# Generated by Django 3.2.6 on 2021-09-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aicontest', '0006_remove_aiproblem_time_limit'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aiproblem',
            table='ai_contest',
        ),
        migrations.AlterModelTable(
            name='aiproblemtag',
            table='ai_contest_tag',
        ),
    ]
