# Generated by Django 3.2.6 on 2021-09-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicontest', '0007_auto_20210903_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproblem',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
