# Generated by Django 3.2.9 on 2021-11-09 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aicontest', '0007_alter_aiproblem_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiproblem',
            name='accepted_number',
        ),
        migrations.RemoveField(
            model_name='aiproblem',
            name='hint',
        ),
        migrations.RemoveField(
            model_name='aiproblem',
            name='io_mode',
        ),
        migrations.RemoveField(
            model_name='aiproblem',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='aiproblem',
            name='memory_limit',
        ),
        migrations.RemoveField(
            model_name='aiproblem',
            name='samples',
        ),
        migrations.RemoveField(
            model_name='aiproblem',
            name='share_submission',
        ),
        migrations.RemoveField(
            model_name='aiproblem',
            name='source',
        ),
        migrations.RemoveField(
            model_name='aiproblem',
            name='spj',
        ),
        migrations.RemoveField(
            model_name='aiproblem',
            name='spj_code',
        ),
        migrations.RemoveField(
            model_name='aiproblem',
            name='spj_compile_ok',
        ),
        migrations.RemoveField(
            model_name='aiproblem',
            name='spj_language',
        ),
        migrations.RemoveField(
            model_name='aiproblem',
            name='spj_version',
        ),
        migrations.RemoveField(
            model_name='aiproblem',
            name='statistic_info',
        ),
        migrations.RemoveField(
            model_name='aiproblem',
            name='submission_number',
        ),
        migrations.RemoveField(
            model_name='aiproblem',
            name='template',
        ),
        migrations.RemoveField(
            model_name='aiproblem',
            name='test_case_id',
        ),
        migrations.RemoveField(
            model_name='aiproblem',
            name='test_case_score',
        ),
        migrations.RemoveField(
            model_name='aiproblem',
            name='total_score',
        ),
    ]
