# Generated by Django 3.2.6 on 2021-09-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicontest', '0008_aiproblem_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproblem',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
