# Generated by Django 3.2.9 on 2021-11-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aicontest', '0008_auto_20211109_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiproblem',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='aiproblem',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='aiproblem',
            name='rule_type',
        ),
    ]
