# Generated by Django 3.2.9 on 2021-11-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicontest', '0009_auto_20211109_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproblem',
            name='accepted_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiproblem',
            name='submission_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
