# Generated by Django 3.2.6 on 2021-09-07 04:30

from django.db import migrations
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('aicontest', '0009_aiproblem_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiproblem',
            old_name='description',
            new_name='contest_description',
        ),
        migrations.RenameField(
            model_name='aiproblem',
            old_name='testhint',
            new_name='data_description',
        ),
        migrations.RemoveField(
            model_name='aiproblem',
            name='summary_description',
        ),
        migrations.AddField(
            model_name='aiproblem',
            name='hint',
            field=utils.models.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='aiproblem',
            name='reward_description',
            field=utils.models.RichTextField(null=True),
        ),
    ]
