# Generated by Django 3.2.6 on 2021-11-12 00:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aicontest', '0010_auto_20211109_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproblem',
            name='join_contest',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
