# Generated by Django 3.2.6 on 2021-08-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0015_rename_hint_problem_testhint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='input_description',
            new_name='summary_description',
        ),
    ]
