# Generated by Django 3.2.6 on 2021-09-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0019_remove_problem_time_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='testhint',
            new_name='hint',
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(null=True),
        ),
    ]
