# Generated by Django 3.2.6 on 2021-11-12 00:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_join_contest',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
